[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php -d memory_limit=512M /var/www/html/artisan queue:work --sleep=1 --timeout=120 --memory=512 --tries=1
numprocs=2
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/laravel-worker.log
stdout_logfile_maxbytes=0
